apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
      - image: hevelmc/playground:v1
        name: playground-app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: playground-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: playground-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: playground-app
            port:
              number: 80
