apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
      - image: hevelmc/playground:v1
        name: playground-app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: svc-playground-app
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: playground-app

